site_name: Leo Weng
site_url: https://www.mkdocs.org/user-guide/configuration/#introduction
repo_url: https://github.com/leoweng111/mkdocs-knowledge-storage
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand
    - navigation.top
    - navigation.path
    # With this, we will not have the content on the right side, which is useful.
    # - toc.integrate
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
    - announce.dismiss

  language: zh
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
      primary: teal
      accent: purple
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
      primary: teal
      accent: lime

nav:
  - "markdown/HomePage.md"
  - 环境配置相关:
    - "markdown/development_utils/开发环境配置及开发流程.md"
    - "markdown/development_utils/配置代码.md"
    - "markdown/development_utils/Linux系统配置.md"
    - "markdown/development_utils/Linux系统软件安装.md"
    - "markdown/development_utils/mongo_test.ipynb"
    - "markdown/development_utils/更新日志.md"
  - 操作技巧:
    - "markdown/operation_utils/mkdocs_guide.md"
    - "markdown/operation_utils/conda操作.md"
    - "markdown/operation_utils/git操作.md"
    - "markdown/operation_utils/OS快捷操作.md"
    - "markdown/operation_utils/Linux基础命令.md"
    - "markdown/operation_utils/Linux常用操作.md"
  - 代码学习:
      - python basic:
        - "markdown/knowledge/code_knowledge/python_basic/python_knowledge.md"
        - "markdown/knowledge/code_knowledge/python_basic/面向对象.ipynb"
        - "markdown/knowledge/code_knowledge/python_basic/对象引用、可变性.ipynb"
        - "markdown/knowledge/code_knowledge/python_basic/datetime_relevant.ipynb"
      - pandas/numpy:
        - "markdown/knowledge/code_knowledge/pandas/pandas_knowledge.md"
      - pytorch:
        - "markdown/knowledge/code_knowledge/pytorch/pytorch_knowledge.md"
      - visualization:
        - "markdown/knowledge/code_knowledge/visualization/matplotlib/matplotlib_relevant.ipynb"
        - "markdown/knowledge/code_knowledge/visualization/plotly.ipynb"
      - algorithm:
        - "markdown/knowledge/code_knowledge/algorithm/堆.ipynb"

  - 深度学习:
    - "markdown/knowledge/deep_learning_notebook/pytorch_basic.ipynb"
    - "markdown/knowledge/deep_learning_notebook/loss_funcs.ipynb"
    - "markdown/knowledge/deep_learning_notebook/CNN.ipynb"
    - "markdown/knowledge/deep_learning_notebook/RNN.ipynb"
    - "markdown/knowledge/deep_learning_notebook/LSTM&GRU.ipynb"
  - 书籍文献阅读:
      - Advanced Financial Machine Learning:
        - "markdown/knowledge/advanced_financial_machine_learning/AFML1.md"
        - "markdown/knowledge/advanced_financial_machine_learning/AFML2.md"
        - "markdown/knowledge/advanced_financial_machine_learning/AFML3.md"
        - "markdown/knowledge/advanced_financial_machine_learning/AFML4.md"
        - "markdown/knowledge/advanced_financial_machine_learning/AFML5.md"
        - "markdown/knowledge/advanced_financial_machine_learning/AFML6.md"
        - "markdown/knowledge/advanced_financial_machine_learning/AFML7.md"
        - "markdown/knowledge/advanced_financial_machine_learning/AFML8.md"
        - "markdown/knowledge/advanced_financial_machine_learning/AFML9.md"
        - "markdown/knowledge/advanced_financial_machine_learning/AFML10.md"
        - "markdown/knowledge/advanced_financial_machine_learning/AFML_summary.md"
  - 面试技巧:
      - brain teasers:
          "markdown/interview_utils/interview_puzzles/brain_teasers.md"
      - python puzzles:
        - "markdown/interview_utils/python_algorithm_puzzles/Alternating Prime Sequence.ipynb"
        - "markdown/interview_utils/python_algorithm_puzzles/Delivery Management System.ipynb"
        - "markdown/interview_utils/python_algorithm_puzzles/Document Chunking.ipynb"
        - "markdown/interview_utils/python_algorithm_puzzles/Extraordinary Substrings.ipynb"
        - "markdown/interview_utils/python_algorithm_puzzles/Frequency Sort.ipynb"
        - "markdown/interview_utils/python_algorithm_puzzles/Keyboard.ipynb"
        - "markdown/interview_utils/python_algorithm_puzzles/Minimum Swaps.ipynb"
        - "markdown/interview_utils/python_algorithm_puzzles/Special Sequence.ipynb"
        - "markdown/interview_utils/python_algorithm_puzzles/Statistic Indicators.ipynb"
        - "markdown/interview_utils/python_algorithm_puzzles/最多放下的长方形.ipynb"
        - "markdown/interview_utils/python_algorithm_puzzles/障碍物岛屿最短路径.ipynb"
        - "markdown/interview_utils/python_algorithm_puzzles/面试遇到的代码题.ipynb"
  - notability笔记:
    - "markdown/knowledge/notability_notes/说明.md"
  - daily:
    - "markdown/daily/current_plan.md"
  - 资料:
      - "markdown/information_material/red_and_green_books.md"
      - "markdown/information_material/useful_books.md"
  - 链接:
      - "markdown/links/package_documents.md"
      - "markdown/links/useful_webs.md"
extra:
  social:
    - icon: simple/gitee
      link: https://www.gitee.com/weng-longao
    - icon: simple/baidu
      link: https://www.baidu.com

#extra_css:
#  - stylesheets/extra.css
#  - css/pdf.css
#
#extra_javascript:
#  - js/pdf.js

extra_templates:
  - templates/pdf.html

plugins:
#  - mkdocs-with-pdf
  - search
  - mkdocs-jupyter:
      include_source: True

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

copyright: Copyright &copy; 2023 <a href="https://github.com/leoweng111" target="_blank" rel="noopener">Leo Weng</a>