site_name: Leo Weng
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand
    - navigation.top
    - navigation.path
    # With this, we will not have the content on the right side, which is useful.想`想`
    # - toc.integrate
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
    - announce.dismiss

  language: zh
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
      primary: teal
      accent: purple
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
      primary: teal
      accent: lime

nav:
  - "markdown/HomePage.md"
  - "markdown/development_utils/开发环境配置及开发流程.md"
  - 操作技巧:
    - "markdown/operation_utils/mkdocs_guide.md"
    - "markdown/operation_utils/conda操作.md"
    - "markdown/operation_utils/git操作.md"
    - "markdown/operation_utils/OS快捷操作.md"
  - 资料:
    - "markdown/information_material/red_and_green_books.md"
    - "markdown/information_material/useful_books.md"
  - 学习:
    - "markdown/knowledge/pandas_knowledge.md"
    - "markdown/knowledge/Exercises_with_solutions.md"
    - "markdown/knowledge/datetime_relevant.ipynb"
  - daily:
    - "markdown/daily/current_plan.md"
extra:
  social:
    - icon: simple/gitee
      link: https://www.gitee.com/weng-longao
    - icon: simple/baidu
      link: https://www.baidu.com

extra_css:
  - stylesheets/extra.css

plugins:
  - mkdocs-jupyter:
      include_source: True

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

copyright: Copyright &copy; 2023 <a href="https://www.gitee.com/weng-longao" target="_blank" rel="noopener">Leo Weng</a>